
version: 2

models:
  - name: sales
    columns:
      - name: date
        description: "The date of the sale"
        tests:
          - not_null
      - name: store_nbr
        description: "The store id"
        tests:
          - not_null
      - name: transactions
        description: "The amount of transactions"
